### ISSUE TITLE
[Ubuntu 16.04] Brightness keys Fn+F5 don't work

### ISSUE THREAD

**Issue by alsar** [alsar/asus-zenbook-ux303-linux#1]
Brightness keys don't work with Ubuntu 16.04.

It seems that this is a long outstanding issue: https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1500094

There have been suggested a few workarounds for this, like:
### Proposal 1:

Updating the GRUB configuration (`/etc/default/grub`):
There have been a few suggestions, with some people reporting that it works for them.
1. `GRUB_CMDLINE_LINUX_DEFAULT="quiet splash acpi_osi="`  or
2. `GRUB_CMDLINE_LINUX_DEFAULT="quiet splash video.use_native_backlight=0"` or
3. `GRUB_CMDLINE_LINUX_DEFAULT="quiet splash pcie_aspm=force acpi_backlight=vendor acpi_osi="`
### Proposal 2:

Adding a file `20-backlight.conf to /usr/share/X11/xorg.conf.d` with:

```
Section "Device"
    Identifier "card0"
    Driver "intel"
    Option "Backlight" "intel_backlight"
    BusID "PCI:0:2:0"
EndSection
```

But nothing works for me.

**Comment by jmmxp** [comment]
Have you tried updating the Linux kernel? I had the exact same problem above for the Zenbook UX303UB and after all 3 changes it was fixed for me.

**Comment by alsar** [comment]
@Jmmxp which kernel version did you use?

**Comment by jmmxp** [comment]
The latest stable version, 4.7.2 http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.7.2/

**Comment by alsar** [comment]
@Jmmxp installed the 4.7.2 kernel but it still doesn't work. What do you have in your grub file under `GRUB_CMDLINE_LINUX_DEFAULT`?

**Comment by jmmxp** [comment]
`GRUB_CMDLINE_LINUX_DEFAULT="quiet splash pcie_aspm=force acpi_osi="`

Also, I just realized that the file I added to `/usr/share/X11/xorg.conf.d` is `20-intel.conf` and not `20-backlight.conf`. I believe this may fix your problem. Inside my conf file is the same contents: 

```
Section "Device"
        Identifier  "card0"
        Driver      "intel"
        Option      "Backlight"  "intel_backlight"
        BusID       "PCI:0:2:0"
EndSection
```

**Comment by alsar** [comment]
Nope. Still doesn't work.

**Comment by rhnvrm** [comment]
@alsar - anything worked for you??

Because, I am now on Fedora 25 with Wayland I can confirm it works out of the box! Highly recommend Fedora!

**Comment by alsar** [comment]
No, none of the workarounds work for me.

**Comment by apollonaute** [comment]
Hi @alsar, 
This feed is a little bit old but did you find any kind of solution? (Same Asus Zenbook on Ubuntu 16.04)
Thank's!!

**Comment by alsar** [comment]
@apollonaute just last week I reinstalled Ubuntu 16.04 (16.04.3) on my ZenBook and I didn't realized just until now that the keys actually do work now.

**Comment by apollonaute** [comment]
Thank's a lot, would you mind giving here the content of your `GRUB_CMDLINE_LINUX_DEFAULT` value in the file `/etc/default/grub`?
Mine is manually set to:
`GRUB_CMDLINE_LINUX_DEFAULT="quiet splash acpi_osi="` with **acpi_osi=** added as you can see. Now, it work's.

**Comment by alsar** [comment]
Mine has the default `GRUB_CMDLINE_LINUX_DEFAULT="quiet splash".
